### PR TITLE
Fix bower.json install blocker

### PR DESCRIPTION
**Pull request by robsterlini**

### CODE REVIEW

**Review by dope — APPROVED** [review]
LGTM

**Comment by theskumar** [comment]
I didn't get what it's trying to fix. how it's fixed. @sterlini-fueled possible you can provide little more info. I'm okay to get this merged none-the-less, it doesn't look much of a change.

**Comment by robsterlini** [comment]
@theskumar You can't have comments in JSON files, so instead of leaving them commented out for the user to enable if they desire; I've adjusted the docs within the `form.js` file to tell them what to add in. The second commit was a JS formatting error that was preventing the `gulp` command to pass, so I've fixed that too! 🎉

**Comment by theskumar** [comment]
Sounds good! :)

**Review by saurabh-fueled — APPROVED** [review]

**Pull request merged**
